name: View
group: Basic
description: >
    View is a general purpose container with no specific semantics that can be used for custom styling purposes. It supports Spectrum style props to ensure consistency with other Spectrum components.
example:
    base: Basic
