name: Button
group: Basic
description: >
    Buttons allow users to perform an action or to navigate to another page.
    They have multiple styles for various needs,
    and are ideal for calling attention to where a user needs to do something in order to move forward in a flow.
examples:
    - key: base
      title: Basic
      description: Basic Usage
    - key: type
      title: Button Type
      Description: Different Button Type
    - key: size
      title: Different Size
