export * from './heading';
export { default as TypographyHeading } from './heading';
export * from './code';
export { default as TypographyCode } from './code';
export * from './detail';
export { default as TypographyDetail } from './detail';
export * from './body';
export { default as TypographyBody } from './body';
export * from './typography';
export { default } from './typography';
export { default as Typography } from './typography';
