name: build doc

on:
    release:
    push:
        branches:
            - 'master'
        tags:
            - '*'

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: actions/setup-node@v1
                with:
                    node-version: 14
            -   name: install
                run: yarn
            -   name: test
                run: npm run test
    build:
        needs:
            - test
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: actions/setup-node@v1
                with:
                    node-version: 14
            -   name: install
                run: yarn
            -   name: build
                run: cd docs && npm run build
            -   name: move out
                run: mv dist /tmp/dist
            -   name: checkout branch
                uses: actions/checkout@v2
                with:
                    ref: pages
            -   name: move in
                run: |
                    rm -rf dist docs
                    mv /tmp/dist ./docs
            -   name: cleanup
                run: |
                    cp ./docs/index.html ./docs/404.html
                    rm -rf ./docs/records.json
                    rm -rf ./docs/*.map
                    cp CNAME ./docs/CNAME
            -   name: commit
                run: |
                    git config user.name github-actions
                    git config user.email github-actions@github.com
                    git add .
                    git commit -m "build ($GITHUB_EVENT_NAME ${GITHUB_REF#*heads/} ${GITHUB_SHA: 0: 8} by $GITHUB_ACTOR $(date "+%Y-%m-%d %H:%M:%S"))"
                    git push
